services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    oc_platform.advert:
        class: OC\PlatformBundle\PlatformServices\OCAdvert
        arguments: [3]
